version: '3'
services:
#####################
### Nginx Proxy
#####################
  nginx:
    restart: unless-stopped
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

      
  node-app:
    restart: unless-stopped
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

    
  mongo:
    restart: unless-stopped
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=deepak
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db


  redis:
    restart: unless-stopped
    image: redis

volumes:
  mongo-db:
